---
# This is a role for setting up the attacker.

- name: Create alias for target
  lineinfile:
    path: '/etc/hosts'
    line: '192.168.20.5 target'

- name: Install packages
  apt:
    pkg:
      - nmap
      - hydra
      - medusa
    update_cache: yes

- name: Add passwords file to the home directory
  copy:
    src: passlist.txt
    dest: /home/user/passlist.txt
    owner: user
    mode: '0644'
...
