---
- hosts: workstation
  become: yes

  vars:
    weak_user: user
    weak_pass: weakpass

  tasks:
    - name: Install SSH
      apt:
        name: openssh-server
        state: present
        update_cache: yes

    - name: Start SSH
      service:
        name: ssh
        state: started
        enabled: yes

    - name: Set weak credentials
      user:
        name: "{{ weak_user }}"
        password: "{{ weak_pass | password_hash('sha512') }}"

    - name: Create SSH folder
      file:
        path: "/home/{{ weak_user }}/.ssh"
        state: directory
        mode: '0700'

    - name: Add private key
      copy:
        content: |
          -----BEGIN RSA PRIVATE KEY-----
          FAKE-PRIVATE-KEY-FOR-LAB
          -----END RSA PRIVATE KEY-----
        dest: "/home/{{ weak_user }}/.ssh/id_rsa"
        mode: '0600'

    - name: Add known_hosts
      copy:
        content: "server ssh-rsa AAAAB3NzaFakeKey"
        dest: "/home/{{ weak_user }}/.ssh/known_hosts"